name: empower_app
description: "Health & Wealth Literacy App for Indian Youth"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Backend & Authentication
  supabase_flutter: ^2.5.6
  crypto: ^3.0.3
  
  # State Management (Flagship upgrade from Provider to Riverpod)
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Local Storage & Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  
  # Networking & API
  dio: ^5.3.2
  dio_cache_interceptor: ^3.4.4
  dio_smart_retry: ^6.0.0
  web_socket_channel: ^2.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  
  # AI & ML Integration
  dart_openai: ^5.1.0
  langchain: ^0.7.3
  langchain_openai: ^0.7.1
  ml_algo: ^16.14.0
  ml_dataframe: ^1.4.1
  tflite_flutter: ^0.10.4
  
  # Health & Fitness APIs
  health: ^10.2.0
  permission_handler: ^11.1.0
  
  # UI & Animations
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  
  # Utilities
  freezed_annotation: ^2.4.1
  uuid: ^4.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  freezed: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # Fonts
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700