/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jqmixqegdtpgimhvovmy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxbWl4cWVnZHRwZ2ltaHZvdm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTIyOTIsImV4cCI6MjA2ODY2ODI5Mn0.VhFIfpsW-w_IQA2gI8yUV9xWyc3j-oWyv0ECbZ9eGsc"